import { Car } from '@/lib/types';

export const STATIC_CARS: Car[] = [
  { _id: 'prado-static', title: 'Toyota Land Cruiser Prado TX-L', slug: { current: 'prado-static' }, status: 'available', condition: 'fresh-import', images: [{ asset: { url: '/cars/prado/prado-01.jpg' } }], price: 7250000, year: 2018, make: 'Toyota', model: 'Prado', bodyType: 'suv', mileage: 62000, transmission: 'automatic', fuelType: 'diesel', _createdAt: '' },
  { _id: 'range-rover-static', title: 'Range Rover Sport HSE', slug: { current: 'range-rover-static' }, status: 'available', condition: 'fresh-import', images: [{ asset: { url: '/cars/range-rover/range-rover-01.jpg' } }], price: 9750000, year: 2019, make: 'Land Rover', model: 'Range Rover Sport', bodyType: 'suv', mileage: 48000, transmission: 'automatic', fuelType: 'petrol', _createdAt: '' },
  { _id: 'gle-static', title: 'Mercedes-Benz GLE 400d AMG Line', slug: { current: 'gle-static' }, status: 'available', condition: 'fresh-import', images: [{ asset: { url: '/cars/gle/gle-01.jpg' } }], price: 12750000, year: 2021, make: 'Mercedes-Benz', model: 'GLE 400d', bodyType: 'suv', mileage: 31000, transmission: 'automatic', fuelType: 'diesel', _createdAt: '' },
  { _id: 'cx5-static', title: 'Mazda CX-5 2.5 AWD', slug: { current: 'cx5-static' }, status: 'available', condition: 'fresh-import', images: [{ asset: { url: '/cars/cx5/cx5-01.jpg' } }], price: 3400000, year: 2020, make: 'Mazda', model: 'CX-5', bodyType: 'suv', mileage: 41000, transmission: 'automatic', fuelType: 'petrol', _createdAt: '' },
  { _id: 'polo-static', title: 'Volkswagen Polo Highline MK7.5', slug: { current: 'polo-static' }, status: 'available', condition: 'fresh-import', images: [{ asset: { url: '/cars/polo/polo-08.jpg' } }], price: 2150000, year: 2019, make: 'Volkswagen', model: 'Polo', bodyType: 'hatchback', mileage: 38000, transmission: 'automatic', fuelType: 'petrol', _createdAt: '' },
  { _id: '3008-static', title: 'Peugeot 3008 Cross City', slug: { current: '3008-static' }, status: 'available', condition: 'fresh-import', images: [{ asset: { url: '/cars/3008/3008-06.jpg' } }], price: 3350000, year: 2020, make: 'Peugeot', model: '3008', bodyType: 'suv', mileage: 44000, transmission: 'automatic', fuelType: 'petrol', _createdAt: '' },
];

export const STATIC_CAR_DETAIL: Record<string, {
  title: string; year: number; price: number; mileage: number;
  transmission: string; fuelType: string; make: string; images: string[];
}> = {
  'prado-static': { title: 'Toyota Land Cruiser Prado TX-L', year: 2018, price: 7250000, mileage: 62000, transmission: 'Automatic', fuelType: 'Diesel', make: 'Toyota', images: ['/cars/prado/prado-01.jpg','/cars/prado/prado-02.jpg','/cars/prado/prado-03.jpg','/cars/prado/prado-04.jpg','/cars/prado/prado-05.jpg'] },
  'range-rover-static': { title: 'Range Rover Sport HSE', year: 2019, price: 9750000, mileage: 48000, transmission: 'Automatic', fuelType: 'Petrol', make: 'Land Rover', images: ['/cars/range-rover/range-rover-01.jpg','/cars/range-rover/range-rover-02.jpg','/cars/range-rover/range-rover-03.jpg','/cars/range-rover/range-rover-04.jpg','/cars/range-rover/range-rover-05.jpg'] },
  'gle-static': { title: 'Mercedes-Benz GLE 400d AMG Line', year: 2021, price: 12750000, mileage: 31000, transmission: 'Automatic', fuelType: 'Diesel', make: 'Mercedes-Benz', images: ['/cars/gle/gle-01.jpg','/cars/gle/gle-02.jpg','/cars/gle/gle-03.jpg','/cars/gle/gle-04.jpg','/cars/gle/gle-05.jpg','/cars/gle/gle-06.jpg','/cars/gle/gle-07.jpg','/cars/gle/gle-08.jpg'] },
  'cx5-static': { title: 'Mazda CX-5 2.5 AWD', year: 2020, price: 3400000, mileage: 41000, transmission: 'Automatic', fuelType: 'Petrol', make: 'Mazda', images: ['/cars/cx5/cx5-01.jpg','/cars/cx5/cx5-02.jpg','/cars/cx5/cx5-03.jpg','/cars/cx5/cx5-04.jpg','/cars/cx5/cx5-05.jpg','/cars/cx5/cx5-06.jpg','/cars/cx5/cx5-07.jpg'] },
  'polo-static': { title: 'Volkswagen Polo Highline MK7.5', year: 2019, price: 2150000, mileage: 38000, transmission: 'Automatic', fuelType: 'Petrol', make: 'Volkswagen', images: ['/cars/polo/polo-08.jpg','/cars/polo/polo-01.jpg','/cars/polo/polo-02.jpg','/cars/polo/polo-03.jpg','/cars/polo/polo-04.jpg','/cars/polo/polo-05.jpg','/cars/polo/polo-06.jpg','/cars/polo/polo-07.jpg'] },
  '3008-static': { title: 'Peugeot 3008 Cross City', year: 2020, price: 3350000, mileage: 44000, transmission: 'Automatic', fuelType: 'Petrol', make: 'Peugeot', images: ['/cars/3008/3008-06.jpg','/cars/3008/3008-01.jpg','/cars/3008/3008-02.jpg','/cars/3008/3008-03.jpg','/cars/3008/3008-04.jpg','/cars/3008/3008-05.jpg','/cars/3008/3008-07.jpg','/cars/3008/3008-08.jpg','/cars/3008/3008-09.jpg'] },
};
